---
- name: Login to oVirt
  ovirt_auth:
    hostname: "{{ rhvm_fqdn }}"
    username: "{{ rhvm_user }}"
    password: "{{ rhvm_password }}"
    ca_file: "{{ rhvm_cafile | default(omit) }}"
    insecure: "{{ rhvm_insecure | default(true) }}"

- name: Create and run VM from template
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    name: "{{ vm_name }}"
    template: "{{ template }}"
    cluster: "{{ cluster }}"
    memory: "{{ vm_memory }}"
    cloud_init:
      dns_servers: '8.8.8.8 8.8.4.4'
      nic_boot_protocol: static
      nic_ip_address: "{{ ip_address }}"
      nic_netmask: "{{ netmask }}"
      nic_gateway: "{{ gateway }}"
      nic_name: eth1 
    high_availability: false
    state: running
    wait: yes

- name: Logout from oVirt
  ovirt_auth:
    state: absent
    ovirt_auth: "{{ ovirt_auth }}"
